### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by TangYuFan** [alibaba/AliOS-Things#1475]
### Contact Details

995435702@qq.com

### What happened?

A bug happened!
运行环境:
haas edu k1 
固件版本:
HaaSPython-HaaSEDUK1-v1.0.2.zip
示例代码：

定义mqtt订阅的回调函数
def mqtt_callback(topic,payload):
    t = topic.decode("utf-8")
    p = payload.decode("utf-8")
    print("on_subcribe: topic is:" + t)
    print("on_subcribe: payload is:" + p)
    #如果是rpc则进行响应

链接mqtt服务端
def connect_tb():
    global client 
    client = mqtt.MQTTClient(client_id=deviceName,user=deviceName,password=deviceToken,server=mqttServerHost,port=mqttServerPort)
    client.connect()
    订阅回调函数
    client.set_callback(mqtt_callback)
    订阅属性更新
    client.subscribe(topic=topic1,qos=1)
    订阅rpc
    client.subscribe(topic=topic2,qos=1)

发送遥测
def telemetryReport(payload):
    client.publish(topic=topic3,msg=payload)
    
发送属性
def attributesReport(payload):
    client.publish(topic=topic4,msg=payload)

定时监听mqtt订阅数据
def waitMsg(delay,id):
    while True:
        client.wait_msg()

if __name__ == '__main__':

    ---------执行数据监听-------
    _thread.start_new_thread(waitMsg,("x","b"))

    while True:
        遥测上报
        payload = {'light':lightness}
        telemetryReport(ujson.dumps(payload))
        utime.sleep(1)

### Version

rel_3.3.0 (Main)

### What soultions are you seeing the problem on?

eduk1_demo

### Relevant log output

```shell
我在 eduk1 设备上执行了 _thread 开启多线程，以 监听 mqtt 的订阅消息等待，造成 python_engine 崩溃：
assert:/home/iot/jenkins/workspace/RTOS-Gerrit-DailyBuild-3.3-new/components/py_engine/engine/py/gc.c:591:gc_free: ATB_GET_KIND(block) == AT_HEAD
Unhandled exception in thread started by <function waitMsg at 0x3405fec0>
Traceback (most recent call last):
  File "/data/pyamp/main.py", line 145, in waitMsg
AssertionError: C-level assert

!!!!!!!!!! Exception  !!!!!!!!!!
crash   time : 2022-04-07 17:49:09
current task : py_engine
========== Regs info  ==========
R0      0x000032B1
R1      0x00000001
R2      0x00000000
R3      0x00BF00E7
R4      0x34069160
R5      0x00000001
R6      0x34069150
R7      0x00000001
R8      0x00000000
R9      0x00000000
R10     0x3405B520
R11     0x00000000
R12     0x34069198
LR      0x0C1437E3
PC      0x0C12BBEC
xPSR    0x01000000
SP      0x3405B278
MSP     0x20162000
PSP     0x3405B210
EXC_RET 0xFFFFFFAC
EXC_NUM 0x00000004
PRIMASK 0x00000000
FLTMASK 0x00000000
BASEPRI 0x00000000
CFSR    0x00000082
HFSR    0x00000000
MMFAR   0x00000010
BFAR    0x00000010
AFSR    0x00000000
========== Call stack ==========
backtrace : 0x0C12BBEC
backtrace : 0x0C1437DE
backtrace : invalid pc : 0x1862
backtrace : invalid pc : 0x1863
========== Heap Info  ==========
---------------------------------------------------------------------------
[HEAP]| TotalSz    | FreeSz     | UsedSz     | MinFreeSz  | MaxFreeBlkSz  |
      | 0x00680000 | 0x005C9F28 | 0x000B60D8 | 0x005B9EF8 | 0x005AB100    |
---------------------------------------------------------------------------
[POOL]| PoolSz     | FreeSz     | UsedSz     | MinFreeSz  | MaxFreeBlkSz  |
      | 0x00000800 | 0x00000000 | 0x00000800 | 0x00000000 | 0x00000100    |
---------------------------------------------------------------------------
========== Task Info  ==========
--------------------------------------------------------------------------
TaskName             State    Prio       Stack      StackSize (MinFree)
--------------------------------------------------------------------------
dyn_mem_proc_task    PEND     0x00000006 0x20053180 0x00000400(0x0000035C)
idle_task            RDY      0x0000003D 0x20053654 0x00001000(0x00000F94)
DEFAULT-WORKQUEUE    PEND     0x00000014 0x20056A38 0x00000C00(0x00000B74)
timer_task           PEND     0x00000005 0x20054928 0x00002000(0x00001F48)
main                 SLP      0x00000021 0x2015A000 0x00005000(0x00004828)
app_thread           PEND     0x0000001F 0x3468A690 0x00001000(0x00000F48)
audio_flinger        PEND     0x0000001E 0x34725404 0x00002000(0x00001F04)
alsa_deamon          PEND     0x0000001F 0x3468EE30 0x00004000(0x00003F08)
transq_msg           PEND     0x0000001F 0x3472B090 0x00001000(0x000008D0)
apps_recover         SLP      0x00000021 0x20051DE4 0x00001000(0x00000F74)
ir_thread            PEND     0x00000021 0x3473213C 0x00002000(0x000019F4)
uart_rx_irq_bottom   PEND     0x00000014 0x34039DD8 0x00001000(0x00000F8C)
net_wq               PEND     0x0000001F 0x20044790 0x00002800(0x00001C30)
net_tasklet          PEND     0x0000001F 0x2004AFD0 0x00002000(0x00001698)
cw1200_bh            PEND     0x0000001F 0x2004F040 0x00001000(0x00000880)
tcpip_thread         PEND     0x0000001F 0x3403F108 0x00006400(0x00005BA8)
wifi_event           PEND     0x00000020 0x3468BA98 0x00001000(0x000008C0)
ash                  SUS      0x0000003C 0x3404B9B0 0x00002000(0x00001FB8)
event_svr            PEND     0x00000020 0x3404F6C0 0x00000800(0x000004BC)
wifi_recvmsg_task    PEND     0x00000021 0x34050A40 0x00001000(0x00000774)
py_engine_task       PEND     0x00000020 0x340535E8 0x00002000(0x00001F58)
py_engine            RDY      0x00000020 0x34056838 0x00005000(0x00004170)
_uart_recv           PEND     0x00000020 0x34008198 0x00000400(0x0000028C)
========== Queue Info ==========
-------------------------------------------------------
QueAddr    TotalSize  PeakNum    CurrNum    TaskWaiting
-------------------------------------------------------
0x34007370 0x00000014 0x00000001 0x00000000 app_thread
0x34007E68 0x00000014 0x00000000 0x00000000 ir_thread
0x3403C4E0 0x00000080 0x00000003 0x00000000 net_wq
0x34045E00 0x00000006 0x00000001 0x00000000 wifi_event
======== Buf Queue Info ========
------------------------------------------------------------------
BufQueAddr TotalSize  PeakNum    CurrNum    MinFreeSz  TaskWaiting
------------------------------------------------------------------
0x20054810 0x000001E0 0x00000000 0x00000000 0x000001E0 timer_task
0x34007708 0x00000100 0x00000000 0x00000000 0x00000100 alsa_deamon
0x3403C808 0x00000028 0x00000000 0x00000000 0x00000028 net_tasklet
0x3403F080 0x00000100 0x00000001 0x00000000 0x000000F8 tcpip_thread
0x3404F608 0x000001E0 0x0000001C 0x00000000 0x00000020 event_svr
0x340509E8 0x00000258 0x00000001 0x00000000 0x00000248 wifi_recvmsg_task
0x340503E8 0x00000078 0x00000000 0x00000000 0x00000078 py_engine_task
0x3400C3C0 0x00000050 0x00000000 0x00000000 0x00000050
========= Sem Waiting ==========
--------------------------------------------
SemAddr    Count      PeakCount  TaskWaiting
--------------------------------------------
0x200547A8 0x00000000 0x00000000 dyn_mem_proc_task
0x20056A08 0x00000000 0x00000000 DEFAULT-WORKQUEUE
0x34686A94 0x00000000 0x00000000 _uart_recv
0x34686ADC 0x00000000 0x00000000 uart_rx_irq_bottom
0x3403DB80 0x00000000 0x00000001 cw1200_bh
Total: 0x0000005E
======== Mutex Waiting =========
--------------------------------------------
MutexAddr  TaskOwner            NestCnt    TaskWaiting
--------------------------------------------
0x34007CB8 py_engineTotal: 0x0000010E
========== Stack info ==========
(0x34056838): 0xDEADBEAF 0x00000000 0x00000000 0x00000000
.........................( All Zeros ).........................
(0x3405A9A8): 0x00000000 0x00000006 0x3405AB1D 0x00000000
(0x3405A9B8): 0x00000004 0x3405AB70 0x2003D038 0x00000003
(0x3405A9C8): 0xFFFFFFF7 0x2003D036 0x3405AA84 0x34008670
(0x3405A9D8): 0x00000000 0x0C20D0FB 0x00000000 0x00000000
(0x3405A9E8): 0x00000000 0x0000000A 0x00000078 0xFFFFFFF6
(0x3405A9F8): 0xFFFFFFF7 0x3405AC8A 0x3405AABC 0x00000006
(0x3405AA08): 0x3405AB75 0x00000006 0x3405AB7D 0x00000000
(0x3405AA18): 0x00000004 0x3405ABD0 0x2003D038 0x00000003
(0x3405AA28): 0xFFFFFFF7 0x2003D036 0x3405AAE4 0x34008670
(0x3405AA38): 0x00000000 0x0C20D0FB 0x00000000 0x00000001
(0x3405AA48): 0x00000064 0x00000001 0x00000064 0xFFFFFFFF
(0x3405AA58): 0xFFFFFFFE 0x3405ACEA 0x3405AB14 0x34008670
(0x3405AA68): 0x00000000 0x0C20C085 0x00000000 0x00000004
(0x3405AA78): 0x00000000 0x00000000 0x00000001 0x00000001
(0x3405AA88): 0x00000000 0x00000001 0x00000000 0x3405ABAF
(0x3405AA98): 0x3405AC98 0x00000000 0x00000000 0x00000000
(0x3405AAA8): 0x00000000 0x00000000 0x00000000 0x00000001
(0x3405AAB8): 0x2C26AF30 0x00000000 0x00000000 0x00000000
(0x3405AAC8): 0x00000000 0x00000000 0x3405AADC 0x00000000
(0x3405AAD8): 0x00000000 0x2003D036 0x00000003 0x00000000
(0x3405AAE8): 0x00000001 0x3405AB3C 0x00000000 0x000001EA
(0x3405AAF8): 0x0000000A 0x00000000 0x2C255DF4 0x00207BB5
(0x3405AB08): 0x3405AB10 0x0C099303 0x00000001 0x00000000
(0x3405AB18): 0x00000000 0x00000001 0x00000000 0x00000000
(0x3405AB28): 0x3405AD9E 0x3405AC04 0x00000000 0x00000000
(0x3405AB38): 0x00000010 0x00000031 0xFFFFFFFF 0x00000088
(0x3405AB48): 0x00000000 0x00000000 0x3405AF78 0x000001EA
(0x3405AB58): 0x3405AD3E 0x00000000 0x00000000 0x00000006
(0x3405AB68): 0x000001EA 0x00000006 0x000001EA 0x00000016
(0x3405AB78): 0x2C259B6E 0x00000000 0x3405AFD0 0xFFFFFFFF
(0x3405AB88): 0x2C259B6E 0x00000006 0x3405ACFD 0x00000000
(0x3405AB98): 0x00000004 0x3405AD50 0x34008670 0x3405AD68
(0x3405ABA8): 0x00000000 0x00000010 0x01010101 0x0C20DD89
(0x3405ABB8): 0x0C20AE08 0x41000000 0x3405AC74 0x34008670
(0x3405ABC8): 0x00000000 0x00000001 0x00000064 0xFFFFFFFF
(0x3405ABD8): 0xFFFFFFFE 0x3405AE6A 0x3405AC94 0x34008670
(0x3405ABE8): 0x0C20AF1D 0x00000000 0x3405AD6A 0x3405AC10
(0x3405ABF8): 0x00000000 0x00000010 0x3405AF08 0x0C20DD89
(0x3405AC08): 0x00000000 0x00000001 0x00000000 0x3405AD2F
(0x3405AC18): 0x3405AE18 0x00000006 0x3405AD8D 0x00000000
(0x3405AC28): 0x3405AD68 0x00000000 0x0C20AF1D 0x00000010
(0x3405AC38): 0x00000000 0x2003D036 0x3405AFB0 0x00000006
(0x3405AC48): 0x00000000 0x2C221244 0x3405AC5C 0x00000000
(0x3405AC58): 0x00000000 0x00000001 0x00000064 0xFFFFFFFF
(0x3405AC68): 0xFFFFFFFE 0x3405AEFA 0x3405AD24 0x34008670
(0x3405AC78): 0x00000000 0x34009EB1 0x00000001 0x00000001
(0x3405AC88): 0x200E29CA 0x00203B43 0x002040FE 0x41000000
(0x3405AC98): 0x002040FE 0x41000000 0x200E41A4 0x200E41A4
(0x3405ACA8): 0x00000001 0x00000001 0x200E599C 0x00000000
(0x3405ACB8): 0x200E01A4 0x00203D1B 0x00000001 0x200E41A4
(0x3405ACC8): 0x00000000 0x00003FE4 0x2003D6B8 0x00000001
(0x3405ACD8): 0x00000001 0x002040F9 0x00000001 0x002040F9
(0x3405ACE8): 0x00000001 0xFFFFFFFF 0x200E297D 0x00000000
(0x3405ACF8): 0x34009EC0 0x00000001 0x00000000 0x34686A7C
(0x3405AD08): 0xFFFFFFFF 0x000000C0 0x0000001A 0x0C0967CD
(0x3405AD18): 0x3405AD44 0x34009EC0 0x00000039 0x34009EC1
(0x3405AD28): 0x34009EC0 0x34009EC1 0x2C298981 0x00000000
(0x3405AD38): 0x3405AE94 0x0C095893 0x00001300 0x00000000
.........................( All Zeros ).........................
(0x3405AD58): 0x3405B840 0x002336A9 0x00000001 0x34009A04
(0x3405AD68): 0x00003130 0x0000001A 0x3405AE80 0x0C0822DF
(0x3405AD78): 0x00000001 0x0C081BCF 0x22400000 0x0C203FA9
(0x3405AD88): 0x34009EC1 0x34009A04 0x2C221099 0x0C204E51
(0x3405AD98): 0x3405AE80 0x0000001A 0x28B33300 0x00000000
(0x3405ADA8): 0x2C2210B2 0x0000001A 0x2C221099 0x3405AE80
(0x3405ADB8): 0x34009A04 0x34009A04 0x00000000 0x00000000
(0x3405ADC8): 0x00000000 0x00000001 0x200530A8 0x00000000
(0x3405ADD8): 0x200E59F8 0x00000007 0x00000000 0xFFFFFFAC
(0x3405ADE8): 0x20040794 0x00000000 0x00000000 0x00000000
.........................( All Zeros ).........................
(0x3405AE08): 0x00000000 0x00000001 0x200530A8 0x00000000
(0x3405AE18): 0x200E59F8 0x00000007 0x00000000 0xFFFFFFAC
(0x3405AE28): 0x20040794 0x00000000 0x00000000 0x00000000
.........................( All Zeros ).........................
(0x3405AE68): 0x00000000 0x10000000 0x0000003D 0x0000003D
(0x3405AE78): 0x00000000 0x002349E9 0x002349E8 0x81000000
(0x3405AE88): 0x447A0000 0x403E0000 0x3F580000 0x35D1CFDC
(0x3405AE98): 0x3331BB4C 0x40000000 0x3F317200 0xB5DDB182
(0x3405AEA8): 0x388AB355 0xBB360B61 0x3E2AAAAB 0x3D1D7DDC
(0x3405AEB8): 0xBFE7523C 0xBE620000 0x0000003D 0x00000000
(0x3405AEC8): 0x00000000 0x002349F7 0x00000005 0x200E5A98
(0x3405AED8): 0x200530A8 0x00234A29 0x00000000 0x00000000
(0x3405AEE8): 0x00000001 0x0C095A97 0x340500D8 0x00000000
(0x3405AEF8): 0x80000000 0x00000001 0x00000000 0x002336D3
(0x3405AF08): 0x00000212 0x00000001 0x3400A318 0x00000001
(0x3405AF18): 0x34068BC0 0x0C0822DF 0x00000212 0x0C1180B5
(0x3405AF28): 0x00000001 0x00000002 0x00000010 0x3400A3A8
(0x3405AF38): 0x00000001 0x34068BC0 0x3400A318 0x00000001
(0x3405AF48): 0x3400A3A8 0x0C1189D5 0x34068BC0 0x00000001
(0x3405AF58): 0x00FFFFFF 0x00000000 0x20040B00 0x00000000
(0x3405AF68): 0x20040A80 0x3405B008 0x00000000 0x3400A3B8
(0x3405AF78): 0x3400049C 0x34046340 0x00000000 0x0C117623
(0x3405AF88): 0x00000001 0x00FFFFFF 0x00000000 0x00000000
(0x3405AF98): 0x00000001 0x002335C3 0x00000000 0x002336D3
(0x3405AFA8): 0x00000003 0x00000000 0x34004F34 0x00000010
(0x3405AFB8): 0x340668DD 0x0C080EFF 0x00000003 0x0C080141
(0x3405AFC8): 0x3405B008 0x00000050 0x3405B008 0x00000002
(0x3405AFD8): 0x34009DB0 0x0C080FBD 0x00FFFFFF 0x0C0958BB
(0x3405AFE8): 0x00000032 0x3405B000 0x3405B008 0x00000032
(0x3405AFF8): 0x00000001 0x002335C3 0xFFFFFFFF 0x34007C88
(0x3405B008): 0x3405B10C 0x3FFFFFFD 0x00000000 0x002336D3
(0x3405B018): 0x34007C88 0x34734454 0x3405B840 0x3FFFFFFD
(0x3405B028): 0x340668DD 0x0C0822DF 0x34007C88 0x0C1437E3
(0x3405B038): 0x3405B124 0x340668E1 0x3405B10C 0x0C12BBC9
(0x3405B048): 0x3405B124 0x0C139363 0x00000000 0x3405B0F8
(0x3405B058): 0x3405B130 0x3405B12C 0x20062D9C 0x00000000
(0x3405B068): 0x3405B124 0x00000020 0x2006331A 0x3405B184
(0x3405B078): 0x00000000 0x00000000 0x3405B0F8 0x3405F260
(0x3405B088): 0x3405B130 0x00000003 0x00000000 0x3405B220
(0x3405B098): 0x00000000 0x3405B050 0x0C138B83 0x0C11EAD5
(0x3405B0A8): 0x00000001 0x002335C3 0xFFFFFFFF 0x34007C88
(0x3405B0B8): 0x3405B0F8 0x00000000 0x00000000 0x002336D3
(0x3405B0C8): 0x34007C88 0x34734454 0x3405B840 0x00000000
(0x3405B0D8): 0x3405B130 0x0C0822DF 0x34007C88 0x0C1437E3
(0x3405B0E8): 0x3405B124 0x00000000 0x3405B0F8 0x00000000
(0x3405B0F8): 0x3405F710 0x34068BB0 0x00000001 0x00000004
(0x3405B108): 0x00000001 0x002335C3 0xFFFFFFFF 0x34007C88
(0x3405B118): 0x3405B21C 0x3FFFFFFD 0x00000000 0x002336D3
(0x3405B128): 0x34007C88 0x34734454 0x3405B840 0x3FFFFFFD
(0x3405B138): 0x3405B21C 0x0C0822DF 0x34007C88 0x0C1437E3
(0x3405B148): 0x3405B230 0x34066E3F 0x3405B21C 0x0C12BBC9
(0x3405B158): 0x3405B230 0x0C139363 0x0000000C 0x3405B208
(0x3405B168): 0x3405B23C 0x3405B238 0x00000385 0x00000000
(0x3405B178): 0x3405B230 0x0000001C 0x00000017 0x3405B294
(0x3405B188): 0x00000385 0x00000000 0x3405B208 0x3405F260
(0x3405B198): 0x3405B240 0x00000002 0x00000000 0x3405B330
(0x3405B1A8): 0x00000000 0x3405B160 0x0C138B83 0x0C11EAD5
(0x3405B1B8): 0x00000001 0x002335C3 0x34734454 0x00000000
(0x3405B1C8): 0x00000001 0x0C12754F 0x0000013E 0x00000008
(0x3405B1D8): 0x0000001D 0x3FFFFFFD 0x0000027D 0x34062480
(0x3405B1E8): 0x0000001D 0x0C128221 0x0000027D 0x0C12E2B9
(0x3405B1F8): 0x20040794 0x00000000 0x0000013E 0x0C12E495
(0x3405B208): 0x3405F7D0 0x42DE9999 0x34734230 0x00000001
(0x3405B218): 0x00000000 0x00BF00E7 0x34069198 0x0C1437E3
(0x3405B228): 0x0C1171D6 0x01000000 0xFFFFFFFF 0x34007C88
(0x3405B238): 0x00000001 0x34069150 0x00000000 0x002336D3
(0x3405B248): 0x34007C88 0x00000000 0x00000000 0x34069150
(0x3405B258): 0x00000001 0x0C0822DF 0x34007C88 0x0C1437E3
(0x3405B268): 0x3405B284 0x34069160 0x00000001 0x0C12BBD9
(0x3405B278): 0x3405B284 0x0C137E41 0x2C27896C 0x00001862
(0x3405B288): 0x000000B4 0x0C137E85 0x000031E5 0x0C1384B1
(0x3405B298): 0x34069150 0x0C137497 0x00000017 0x0C128441
(0x3405B2A8): 0x00000001 0x00002F92 0x00000000 0x000005F2
(0x3405B2B8): 0x3405B340 0x34060030 0x34060034 0x00002F92
(0x3405B2C8): 0x34060030 0x00000000 0x34734454 0x00000000
(0x3405B2D8): 0x00000001 0x0C12754F 0x0C12F885 0x00000010
(0x3405B2E8): 0x2C279744 0x34069110 0x00000001 0x2C27869C
(0x3405B2F8): 0x00000000 0x0C128221 0x00000000 0x0C1373D5
(0x3405B308): 0x34069110 0x00000000 0x34069130 0x34069130
(0x3405B318): 0x00000001 0x0C12C873 0x34069110 0x00000001
(0x3405B328): 0x3405B418 0x0C137021 0x00000001 0x34064CB5
(0x3405B338): 0x3405B414 0x3FFFFFFD 0x34064CB4 0x2C27869C
(0x3405B348): 0x00000000 0x0C1397CB 0x3405B41C 0x3405B3F8
(0x3405B358): 0x3405B424 0x3405B420 0x3405B428 0x00000000
(0x3405B368): 0x3405B418 0x0000001F 0x3405B41C 0x3405B47C
(0x3405B378): 0x34068C00 0x00000000 0x3405B3F8 0x3405E9E0
(0x3405B388): 0x3405B428 0x00000002 0x00000000 0x3405B520
(0x3405B398): 0x00000000 0x3405B350 0x0C138B83 0x0C11EAD5
(0x3405B3A8): 0x00000001 0x002335C3 0xFFFFFFFF 0x34007C88
(0x3405B3B8): 0x3405B3F8 0x3405E9E0 0x00000000 0x002336D3
(0x3405B3C8): 0x34007C88 0x34734454 0x3405B840 0x3405E9E0
(0x3405B3D8): 0x3405B428 0x00000000 0x3405B3F8 0x3405E9E0
(0x3405B3E8): 0x3405B428 0x00000002 0x00000000 0x0C12E7AB
(0x3405B3F8): 0x3405ECC0 0x34064CB3 0x3405B408 0x00000006
(0x3405B408): 0x3405E9E0 0x2C289FFC 0x3405FED0 0x2C277C20
(0x3405B418): 0x34069110 0x00000167 0x34060030 0x0C12E745
(0x3405B428): 0x3FFFFFFD 0x340646B0 0x3405B520 0x340646B7
(0x3405B438): 0x3405B51C 0x3FFFFFFD 0x340646B6 0x2C27869C
(0x3405B448): 0x00000000 0x3405B630 0x00000000 0x0C139861
(0x3405B458): 0x3405B534 0x3405B500 0x3405B540 0x3405B53C
(0x3405B468): 0x3405B540 0x00000000 0x3405B534 0x00000009
(0x3405B478): 0x3405B534 0x3405B594 0x00000000 0x00000000
(0x3405B488): 0x3405B500 0x3405E9E0 0x3405B540 0x00000001
(0x3405B498): 0x00000000 0x3405B630 0x00000000 0x3405B458
(0x3405B4A8): 0x0C138B83 0x0C11EAD5 0x00000001 0x002335C3
(0x3405B4B8): 0xFFFFFFFF 0x34007C88 0x3405B500 0x3405E9E0
(0x3405B4C8): 0x00000000 0x002336D3 0x34007C88 0x34734454
(0x3405B4D8): 0x3405B840 0x3405E9E0 0x3405B540 0x00000000
(0x3405B4E8): 0x3405B500 0x3405E9E0 0x3405B540 0x00000001
(0x3405B4F8): 0x00000000 0x0C12E7AB 0x3405EDD0 0x340646B5
(0x3405B508): 0x3405B510 0x0000000B 0x3473452C 0x00000011
(0x3405B518): 0x00000007 0x3405ECC0 0x34060030 0x00000167
(0x3405B528): 0x00000007 0x00000107 0x00000107 0x34069070
(0x3405B538): 0x00000007 0x34060030 0x3FFFFFFD 0x340610F1
(0x3405B548): 0x3405B630 0x340610F3 0x3405B62C 0x3FFFFFFD
(0x3405B558): 0x340610F2 0x2C27869C 0x3405B62C 0x00000000
(0x3405B568): 0x00000000 0x0C139861 0x00000002 0x3405B618
(0x3405B578): 0x3405B640 0x3405B63C 0x00000002 0x00000000
(0x3405B588): 0x3405B634 0x00000016 0x2C275B34 0x3405B68C
(0x3405B598): 0x3405B618 0x00000000 0x3405B618 0x3473452C
(0x3405B6D8): 0x3405B700 0x00000001 0x00000002 0x340567C0
(0x3405B6E8): 0x0000057D 0x3405B700 0x3405B700 0x0C08E367
(0x3405B6F8): 0x00000005 0x3405E980 0x7461642F 0x79702F61
(0x3405B708): 0x2F706D61 0x6E69616D 0x0079702E 0x00000000
.........................( All Zeros ).........................
(0x3405B7F8): 0x00000000 0x00000000 0x34056798 0x05050505
(0x3405B808): 0x06060606 0x07070707 0x08080808 0x0C08E413
(0x3405B818): 0x34056798 0x01010101 0x02020202 0x03030303
(0x3405B828): 0x12121212 0x04040404 0x05050505 0x00235149
!!!!!!!!!! dump end   !!Exception in thread rx:
Traceback (most recent call last):
  File "C:\ProgramData\aos\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\aos\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\aos\miniconda3\lib\site-packages\serial\tools\miniterm.py", line 499, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "C:\ProgramData\aos\miniconda3\lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
```

**Comment by skylarCai** [comment]
感谢您提出的宝贵问题，我们有7x24小时服务的“HaaS百事通”客服系统，
    您可以先尝试能否解决您的问题(https://haas.iot.aliyun.com/?ask=1&f=a2cre.b82925042)

    如果“HaaS百事通”没有解决您的问题，请回复“人工支持”，我们会在工作日(10:00-12:00/14:00-18:00)10分钟内回复您。

**Comment by TangYuFan** [comment]
已经解决
